# Generated by Django 3.1.7 on 2021-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_questionpackage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreatedQuizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_looked_at', models.BooleanField()),
            ],
        ),
    ]
