# Generated by Django 3.1.7 on 2021-07-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_questionpackage_show_in_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpackage',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
