# Generated by Django 3.1.7 on 2021-07-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questionpackage_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpackage',
            name='played',
        ),
    ]
