# Generated by Django 3.1.7 on 2021-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_questionpackage_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpackage',
            name='played',
            field=models.IntegerField(default=0),
        ),
    ]
