# Generated by Django 3.1.7 on 2021-07-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_questionpackage_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpackage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Text'),
        ),
    ]
